frontend/controllers/FrontendController.php
<?php

namespace frontend\controllers;

use frontend\helpers\CacheHelper;
use Yii;
use yii\web\Controller;
use yii\web\Response;

/**
 * Class FrontendController
 * @package frontend\controllers
 */
class FrontendController extends Controller
{
    protected $modelSearchClass = 'empty-search-class';

    /**
     * @param string $redirectTo
     *
     * @return Response
     */
    public function actionClearFilter(string $redirectTo = 'index'): Response
    {
        Yii::$app->cache->delete(CacheHelper::withUserPostfix($this->modelSearchClass));

        return $this->redirect([$redirectTo]);
    }
}

frontend/controllers/SubdivisionController.php
<?php

namespace frontend\controllers;

use common\models\subdivision\Subdivision;
use common\services\SubdivisionServiceInterface;
use DomainException;
use frontend\forms\subdivision\SubdivisionForm;
use frontend\helpers\FilterHelper;
use frontend\traits\FlashTrait;
use frontend\models\subdivision\SubdivisionSearch;
use Yii;
use yii\base\InvalidConfigException;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class SubdivisionController
 * @package frontend\controllers
 */
class SubdivisionController extends FrontendController
{
    use FlashTrait;

    private $_subdivisionService;

    /**
     * SubdivisionController constructor.
     *
     * @param $id
     * @param $module
     * @param SubdivisionServiceInterface $subdivisionService
     * @param array $config
     */
    public function __construct(
        $id,
        $module,
        SubdivisionServiceInterface $subdivisionService,
        $config = []
    )
    {
        $this->_subdivisionService = $subdivisionService;
        $this->modelSearchClass = SubdivisionSearch::class;
        parent::__construct($id, $module, $config);
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'update', 'create', 'archive', 'restore', 'clear-filter'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new SubdivisionSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'showFilter' => FilterHelper::isShow(FilterHelper::TYPE_SUBDIVISION_FILTER),
        ]);
    }

    /**
     * @return string|Response
     * @throws InvalidConfigException
     */
    public function actionCreate()
    {
        $modelForm = Yii::createObject(SubdivisionForm::class);
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess();
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('create', [
            'modelForm' => $modelForm,
        ]);
    }

    /**
     * @param $id
     *
     * @return string|Response
     * @throws NotFoundHttpException
     * @throws InvalidConfigException
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelForm = Yii::createObject(SubdivisionForm::class, ['subdivision' => $model]);
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess();
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('update', [
            'model' => $model,
            'modelForm' => $modelForm,
        ]);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionArchive($id): Response
    {
        $this->_subdivisionService->changeStatus($id, Subdivision::STATUS_ARCHIVE)
            ? $this->flashSuccess('Подразделение помещено в архив')
            : $this->flashError('Ошибка помещения подразделения в архив');

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionRestore($id): Response
    {
        $this->_subdivisionService->changeStatus($id, Subdivision::STATUS_ACTIVE)
            ? $this->flashSuccess('Подразделение восстановленно')
            : $this->flashError('Ошибка восстановления подразделения');

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Subdivision|null
     * @throws NotFoundHttpException
     */
    protected function findModel($id): ?Subdivision
    {
        if (($model = Subdivision::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/views/subdivision/_form.php
<?php

use common\models\subdivision\Subdivision;
use frontend\forms\subdivision\SubdivisionForm;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;

/**
 * @var $this View
 * @var $modelForm SubdivisionForm
 * @var $form ActiveForm
 */
?>

<div class="bid-form">
    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'name')->textInput() ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'status')->dropDownList(Subdivision::getStatusLabels()) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>
    <?php $form::end(); ?>
</div>

frontend/views/subdivision/_search.php
<?php

use frontend\helpers\FilterHelper;
use common\models\subdivision\Subdivision;
use frontend\models\subdivision\SubdivisionSearch;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;

/**
 * @var $this View
 * @var $model SubdivisionSearch
 * @var $form ActiveForm
 * @var $showFilter boolean
 */
?>

<div class="panel panel-default">
    <div class="panel-heading search-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
        <h4 class="panel-title">
            <a class="accordion-toggle <?= $showFilter ? '' : 'collapsed' ?>" data-toggle="collapse"
               data-parent="#accordion" href="#collapseThree">Фильтр</a>
        </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse <?= $showFilter ? 'in' : '' ?>"
         data-filter-type="<?= FilterHelper::TYPE_SUBDIVISION_FILTER ?>">
        <div class="panel-body">
            <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
            ]); ?>
            <div class="row">
                <div class="col-sm-3">
                    <?= $form->field($model, 'name') ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'status')->dropDownList(Subdivision::getStatusLabels(), [
                        'prompt' => '---'
                    ]) ?>
                </div>
                <div class="col-sm-3"></div>
                <div class="col-sm-3">
                    <div class="form-group t-a-r m-t-25">
                        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Сбросить', ['/subdivision/clear-filter'], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/subdivision/create.php
<?php

use frontend\forms\subdivision\SubdivisionForm;
use yii\web\View;

/**
 * @var $this View
 * @var $modelForm SubdivisionForm
 */

$this->title = 'Добавление подразделения';
$this->params['breadcrumbs'][] = ['label' => 'Подразделения', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="bid-create">
    <h1 class="t-a-c m-t-0">
        <?= h($this->title) ?>
    </h1>

    <?= $this->render('_form', [
        'modelForm' => $modelForm,
    ]) ?>
</div>

frontend/views/subdivision/index.php
<?php

use common\models\subdivision\Subdivision;
use frontend\models\subdivision\SubdivisionSearch;
use kartik\dynagrid\DynaGrid;
use yii\helpers\Html;
use yii\data\ActiveDataProvider;
use yii\web\View;

/**
 * @var $dataProvider ActiveDataProvider
 * @var $this View
 * @var $searchModel SubdivisionSearch
 * @var $showFilter boolean
 */

$this->title = 'Список подразделений';
$this->params['breadcrumbs'][] = $this->title;

$columns = [
    [
        'attribute' => 'id',
        'label' => 'ID',
        'value' => function (Subdivision $model) {
            return $model->id;
        }
    ],
    [
        'attribute' => 'name',
        'format' => 'raw',
        'value' => function (Subdivision $model) {
            return $model->name;
        }
    ],
    [
        'attribute' => 'status',
        'format' => 'raw',
        'value' => function (Subdivision $model) {
            switch ($model->status) {
                case Subdivision::STATUS_ACTIVE:
                    return '<span class="label label-primary">' . $model->getStatusLabel() . '</span>';
                case Subdivision::STATUS_ARCHIVE:
                    return '<span class="label label-danger">' . $model->getStatusLabel() . '</span>';
                default:
                    return $model->getStatusLabel();
            }
        }
    ],
    [
        'class' => 'yii\grid\ActionColumn',
        'header' => 'Действия',
        'headerOptions' => [
            'width' => '100',
        ],
        'template' => '{update} {archive}',
        'buttons' => [
            'update' => function ($url) {
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                    'title' => 'Обновить',
                    'class' => 'btn btn-xs btn-primary'
                ]);
            },
            'archive' => function ($url, Subdivision $model) {
                if ($model->isActive()) {
                    return Html::a('<i class="fa fa-archive"></i>', $url, [
                        'title' => 'Архивировать',
                        'class' => 'btn btn-xs btn-danger',
                        'data-confirm' => 'Вы действительно хотите архивировать подразделение?'
                    ]);
                }

                if ($model->isArchive()) {
                    return Html::a('<i class="fa fa-check"></i>', ['/subdivision/restore', 'id' => $model['id']], [
                        'title' => 'Восстановить',
                        'class' => 'btn btn-xs btn-warning',
                        'data-confirm' => 'Вы действительно хотите восстановить данное подразделение?'
                    ]);
                }
            },
        ],
    ],
];
?>

<h1 class="t-a-c m-t-0">
    <?= h($this->title) ?>
</h1>

<?= $this->render('_search', [
    'model' => $searchModel,
    'showFilter' => $showFilter,
]); ?>

<?= DynaGrid::widget([
    'columns' => $columns,
    'theme' => 'simple-default',
    'storage' => DynaGrid::TYPE_COOKIE,
    'gridOptions' => [
        'dataProvider' => $dataProvider,
        'panel' => [
            'heading' => '<h3 class="panel-title">' . $this->title . '</h3>',
            'before' => '<div class="dynagrid-buttons">' . '{dynagrid}' .
                Html::a('Добавить подразделение', ['create'], ['class' => 'btn btn-default m-l-5 m-r-5']) . '</div>'
        ],
    ],
    'options' => [
        'id' => 'dynagrid-subdivision'
    ]
]); ?>

frontend/views/subdivision/update.php
<?php

use common\helpers\TextHelper;
use common\models\subdivision\Subdivision;
use frontend\forms\subdivision\SubdivisionForm;
use yii\web\View;

/**
 * @var $this View
 * @var $modelForm SubdivisionForm
 * @var $model Subdivision
 */

$this->title = 'Редактирование подразделения: ' . TextHelper::getShortText($model->name, 75);
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="bid-update">
    <h1 class="m-t-0">
        <?= h($this->title) ?>
    </h1>

    <?= $this->render('_form', [
        'modelForm' => $modelForm,
    ]) ?>
</div>