frontend/controllers/BidController.php
<?php

namespace frontend\controllers;

use common\models\rbac\AuthItem;
use common\models\bid\Bid;
use common\services\BidServiceInterface;
use DomainException;
use frontend\forms\bid\BidForm;
use frontend\helpers\FilterHelper;
use frontend\traits\FlashTrait;
use frontend\models\bid\BidSearch;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class BidController
 * @package frontend\controllers
 */
class BidController extends FrontendController
{
    use FlashTrait;

    private $bidService;

    /**
     * BidController constructor.
     *
     * @param $id
     * @param $module
     * @param BidServiceInterface $service
     * @param array $config
     */
    public function __construct(
        $id,
        $module,
        BidServiceInterface $service,
        $config = []
    )
    {
        $this->bidService = $service;
        $this->modelSearchClass = BidSearch::class;
        parent::__construct($id, $module, $config);
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'update', 'create', 'check', 'work', 'clear-filter'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['archive'],
                        'allow' => true,
                        'roles' => [AuthItem::ROLE_ADMIN],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new BidSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'showFilter' => FilterHelper::isShow(FilterHelper::TYPE_BID_FILTER),
        ]);
    }

    /**
     * @param $id
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id): string
    {
        $model = Bid::find()->with('statusHistory')->andWhere(['id' => $id])->one();
        if ($model === null) {
            throw new NotFoundHttpException('Заявка не найдена');
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|Response
     * @throws Exception
     */
    public function actionCreate()
    {
        $modelForm = Yii::createObject(BidForm::class);
        $modelForm->setDate()->setNumber();
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess('Заявка создана');
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('create', [
            'modelForm' => $modelForm,
            'lastAcceptedUser' => Bid::getLastAcceptedUser(),
        ]);
    }

    /**
     * @param $id
     *
     * @return string|Response
     * @throws NotFoundHttpException
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelForm = Yii::createObject(BidForm::class, ['bid' => $model]);
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess('Заявка обновлена');
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('update', [
            'model' => $model,
            'modelForm' => $modelForm,
            'lastAcceptedUser' => Bid::getLastAcceptedUser(),
        ]);
    }

    /**
     * @param int $id
     *
     * @return Response
     */
    public function actionArchive(int $id): Response
    {
        try {
            $this->bidService->changeStatus($id, Bid::STATUS_ARCHIVE);
            $this->flashSuccess('Заявка помещена в архив');
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionCheck($id): Response
    {
        try {
            $this->bidService->changeStatus($id, Bid::STATUS_COMPLETE);
            $this->flashSuccess('Заявка исполнена');
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionWork($id): Response
    {
        try {
            $this->bidService->changeStatus($id, Bid::STATUS_IN_WORK);
            $this->flashSuccess('Заявка принята в работу');
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Bid|null
     * @throws NotFoundHttpException
     */
    protected function findModel($id): ?Bid
    {
        if (($model = Bid::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/DocsController.php
<?php

namespace frontend\controllers;

use common\models\phoneBook\PhoneBook;
use common\services\SoftDeleteServiceInterface;
use DomainException;
use frontend\forms\phoneBook\PhoneBookForm;
use frontend\helpers\FilterHelper;
use frontend\traits\FlashTrait;
use Yii;
use yii\base\InvalidConfigException;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;

/**
 * Class DocsController
 * @package frontend\controllers
 */
class DocsController extends Controller
{
    use FlashTrait;

    private $_softDeleteService;

    /**
     * DocsController constructor.
     *
     * @param $id
     * @param $module
     * @param SoftDeleteServiceInterface $softDeleteService
     * @param array $config
     */
    public function __construct(
        $id,
        $module,
        SoftDeleteServiceInterface $softDeleteService,
        $config = []
    )
    {
        $this->_softDeleteService = $softDeleteService;
        parent::__construct($id, $module, $config);
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string|Response
     * @throws InvalidConfigException
     */
    public function actionIndex()
    {
        $modelForm = Yii::createObject(PhoneBookForm::class);
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess();
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('index', [
            'modelForm' => $modelForm,
            'phones' => PhoneBook::getAllPhones(),
            'showFilter' => FilterHelper::isShow(FilterHelper::TYPE_PHONE_BOOK_FILTER),
        ]);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionDelete($id): Response
    {
        try {
            $this->_softDeleteService->softDelete($id, PhoneBook::class);
            $this->flashSuccess();
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }
}

frontend/controllers/EventsController.php
<?php

namespace frontend\controllers;

use common\models\event\Events;
use common\models\rbac\AuthItem;
use common\services\SoftDeleteServiceInterface;
use DomainException;
use frontend\forms\events\EventsForm;
use frontend\helpers\FilterHelper;
use frontend\models\statistics\DateForm;
use frontend\models\event\EventsSearch;
use frontend\traits\FlashTrait;
use Yii;
use yii\base\InvalidConfigException;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class EventsController
 * @package frontend\controllers\admin
 */
class EventsController extends FrontendController
{
    use FlashTrait;

    private $_softDeleteService;

    /**
     * EventsController constructor.
     *
     * @param $id
     * @param $module
     * @param SoftDeleteServiceInterface $softDeleteService
     * @param array $config
     */
    public function __construct(
        $id,
        $module,
        SoftDeleteServiceInterface $softDeleteService,
        $config = []
    )
    {
        $this->_softDeleteService = $softDeleteService;
        $this->modelSearchClass = DateForm::class;
        parent::__construct($id, $module, $config);
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'clear-filter', 'create', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws InvalidConfigException
     */
    public function actionIndex(): string
    {
        $this->view->params['layout-classes'] = 'w-1500';

        $dateForm = new DateForm();
        $dateForm->load(Yii::$app->request->queryParams);
        $searchModel = Yii::createObject(EventsSearch::class, ['dateForm' => $dateForm]);

        return $this->render('index', [
            'currentDay' => date('Y-m-d'),
            'dateForm' => $dateForm,
            'events' => $searchModel->search(Yii::$app->request->queryParams),
            'period' => $dateForm->generatePeriod(),
            'searchModel' => $searchModel,
            'showFilter' => FilterHelper::isShow(FilterHelper::TYPE_EVENTS_FILTER),
        ]);
    }

    /**
     * @return Response
     * @throws InvalidConfigException
     */
    public function actionCreate(): Response
    {
        $modelForm = Yii::createObject(EventsForm::class);
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess();
            } else {
                throw new DomainException('Ошибка сохранения события');
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Response
     * @throws \Throwable
     */
    public function actionDelete($id): Response
    {
        try {
            $this->_softDeleteService->softDelete($id, Events::class);
            $this->flashSuccess();
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Events|null
     * @throws NotFoundHttpException
     */
    protected function findModel($id): ?Events
    {
        if (($model = Events::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/StatisticsController.php
<?php

namespace frontend\controllers;

use frontend\helpers\FilterHelper;
use frontend\models\statistics\DateForm;
use frontend\services\MainStatisticsServiceInterface;
use Yii;
use yii\base\InvalidConfigException;
use yii\filters\AccessControl;

/**
 * Class StatisticsController
 * @package frontend\controllers
 */
class StatisticsController extends FrontendController
{
    private $_mainStatisticsService;

    /**
     * StatisticsController constructor.
     *
     * @param $id
     * @param $module
     * @param MainStatisticsServiceInterface $mainStatisticsService
     * @param array $config
     */
    public function __construct(
        $id,
        $module,
        MainStatisticsServiceInterface $mainStatisticsService,
        $config = []
    )
    {
        $this->_mainStatisticsService = $mainStatisticsService;
        $this->modelSearchClass = DateForm::class;
        parent::__construct($id, $module, $config);
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'clear-filter'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     * @throws InvalidConfigException
     */
    public function actionIndex(): string
    {
        $dateForm = Yii::createObject(DateForm::class);
        $dateForm->load(Yii::$app->request->queryParams);
        $this->_mainStatisticsService->setDateForm($dateForm);

        return $this->render('index', [
            'dateForm' => $dateForm,
            'showFilter' => FilterHelper::isShow(FilterHelper::TYPE_STATISTICS_FILTER),
            'countBidStat' => $this->_mainStatisticsService->countBidStat(),
            'buildingStat' => $this->_mainStatisticsService->buildingStat(),
            'departmentStat' => $this->_mainStatisticsService->departmentStat(),
            'subdivisionStat' => $this->_mainStatisticsService->subdivisionStat(),
        ]);
    }
}

frontend/views/layouts/_modals.php
<div class="modal fade" id="common-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content"></div>
    </div>
</div>
<div class="modal fade" id="common-modal-small" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content"></div>
    </div>
</div>

frontend/views/layouts/header.php
<?php

use yii\helpers\Html;
use yii\web\View;

/**
 * @var $this View
 * @var $content string
 */

$user = Yii::$app->user->identity;
$isGuest = $this->params['global-is-guest'] ?? false;
$isAdmin = $this->params['global-is-admin'] ?? false;
$bidCount = $this->params['statistics-bid-count'] ?? 0;
$userCount = $this->params['statistics-user-count'] ?? 0;
$todayCountEvents = $this->params['statistics-today-count-events'] ?? 0;
$projectName = Yii::$app->params['projectName'];
?>

<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button"
                    class="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#navbar"
                    aria-expanded="false"
                    aria-controls="navbar">
                <span class="sr-only">Навигация</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <?= Html::a(h($projectName), ['/'], [
                'class' => 'navbar-brand',
            ]) ?>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <?php if (!$isGuest) { ?>
                    <li>
                        <?= Html::a('Новая заявка', ['/bid/create']) ?>
                    </li>
                    <li>
                        <?php if ($bidCount > 0) { ?>
                            <?= Html::a("Заявки&nbsp;({$bidCount})", ['/bid/index']) ?>
                        <?php } else { ?>
                            <?= Html::a("Заявки", ['/bid/index']) ?>
                        <?php } ?>
                    </li>
                    <li>
                        <?php if ($todayCountEvents > 0) { ?>
                            <?= Html::a("События&nbsp;({$todayCountEvents})", ['/events/index']) ?>
                        <?php } else { ?>
                            <?= Html::a("События", ['/events/index']) ?>
                        <?php } ?>
                    </li>
                    <li>
                        <?= Html::a('Статистика', ['/statistics/index']) ?>
                    </li>
                    <li>
                        <?= Html::a('Справочник', ['/docs/index']) ?>
                    </li>
                    <li>
                        <?php if ($user->profile->isReadNotes()) { ?>
                            <?= Html::a('<i class="far fa-sticky-note"></i>', ['/note'], [
                                'title' => 'Заметки',
                                'data' => [
                                    'toggle' => 'tooltip',
                                    'placement' => 'bottom',
                                ],
                            ]) ?>
                        <?php } else { ?>
                            <?= Html::a('<i class="fas fa-sticky-note text-danger"></i>', ['/note'], [
                                'title' => 'Заметки',
                                'data' => [
                                    'toggle' => 'tooltip',
                                    'placement' => 'bottom',
                                ],
                            ]) ?>
                        <?php } ?>
                    </li>
                <?php } else { ?>
                    <li>
                        <?= Html::a('Справочник', ['/docs/index']) ?>
                    </li>
                <?php } ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <?php if ($isGuest) { ?>
                    <li>
                        <?= Html::a('Авторизация', ['/login']) ?>
                    </li>
                <?php } else { ?>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle"
                           data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false"><?= $user->username ?>
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>
                                <?= Html::a('ЛК', ['/profile']) ?>
                            </li>
                            <?php if ($isAdmin) { ?>
                                <li>
                                    <?php if ($userCount > 0) { ?>
                                        <?= Html::a("Пользователи&nbsp;({$userCount})", ['/admin/user/index']) ?>
                                    <?php } else { ?>
                                        <?= Html::a("Пользователи", ['/admin/user/index']) ?>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                            <li>
                                <?= Html::a('Подразделения', ['/subdivision/index']) ?>
                            </li>
                            <li role="separator" class="divider"></li>
                            <li>
                                <?= Html::a('CHANGELOG', ['/changelog']) ?>
                            </li>
                            <li>
                                <?= Html::a('Выйти(' . $user->username . ')', ['/site/logout']) ?>
                            </li>
                        </ul>
                    </li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>

frontend/views/layouts/main.php
<?php

use common\widgets\AlertJbox;
use yii\helpers\Html;
use yii\web\View;
use frontend\assets\AppAsset;
use yii\widgets\Breadcrumbs;

/**
 * @var $this View
 * @var $content string
 */

AppAsset::register($this);
$layoutClasses = $this->params['layout-classes'];
?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= h($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<div class="fon"></div>
<?php $this->beginBody() ?>

<div class="wrap">
    <?= $this->render('header.php') ?>
    <div class="container m-t-70">
        <?= Breadcrumbs::widget(['links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : []]); ?>
    </div>
    <div class="container <?= $layoutClasses ?>">
        <?= AlertJbox::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= h(Yii::$app->params['projectName']) ?> <?= date('Y') ?></p>
    </div>
</footer>

<?= $this->render('_modals') ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>