frontend/controllers/BidController.php
<?php

namespace frontend\controllers;

use common\models\rbac\AuthItem;
use common\models\bid\Bid;
use common\services\BidServiceInterface;
use DomainException;
use frontend\forms\bid\BidForm;
use frontend\helpers\FilterHelper;
use frontend\traits\FlashTrait;
use frontend\models\bid\BidSearch;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Class BidController
 * @package frontend\controllers
 */
class BidController extends FrontendController
{
    use FlashTrait;

    private $bidService;

    /**
     * BidController constructor.
     *
     * @param $id
     * @param $module
     * @param BidServiceInterface $service
     * @param array $config
     */
    public function __construct(
        $id,
        $module,
        BidServiceInterface $service,
        $config = []
    )
    {
        $this->bidService = $service;
        $this->modelSearchClass = BidSearch::class;
        parent::__construct($id, $module, $config);
    }

    /**
     * @return array
     */
    public function behaviors(): array
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['index', 'view', 'update', 'create', 'check', 'work', 'clear-filter'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['archive'],
                        'allow' => true,
                        'roles' => [AuthItem::ROLE_ADMIN],
                    ],
                ],
            ],
        ];
    }

    /**
     * @return string
     */
    public function actionIndex(): string
    {
        $searchModel = new BidSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'showFilter' => FilterHelper::isShow(FilterHelper::TYPE_BID_FILTER),
        ]);
    }

    /**
     * @param $id
     *
     * @return string
     * @throws NotFoundHttpException
     */
    public function actionView($id): string
    {
        $model = Bid::find()->with('statusHistory')->andWhere(['id' => $id])->one();
        if ($model === null) {
            throw new NotFoundHttpException('Заявка не найдена');
        }

        return $this->render('view', [
            'model' => $model,
        ]);
    }

    /**
     * @return string|Response
     * @throws Exception
     */
    public function actionCreate()
    {
        $modelForm = Yii::createObject(BidForm::class);
        $modelForm->setDate()->setNumber();
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess('Заявка создана');
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('create', [
            'modelForm' => $modelForm,
            'lastAcceptedUser' => Bid::getLastAcceptedUser(),
        ]);
    }

    /**
     * @param $id
     *
     * @return string|Response
     * @throws NotFoundHttpException
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $modelForm = Yii::createObject(BidForm::class, ['bid' => $model]);
        try {
            if ($modelForm->load(Yii::$app->request->post()) && $modelForm->save()) {
                $this->flashSuccess('Заявка обновлена');
                return $this->redirect(['index']);
            }
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->render('update', [
            'model' => $model,
            'modelForm' => $modelForm,
            'lastAcceptedUser' => Bid::getLastAcceptedUser(),
        ]);
    }

    /**
     * @param int $id
     *
     * @return Response
     */
    public function actionArchive(int $id): Response
    {
        try {
            $this->bidService->changeStatus($id, Bid::STATUS_ARCHIVE);
            $this->flashSuccess('Заявка помещена в архив');
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionCheck($id): Response
    {
        try {
            $this->bidService->changeStatus($id, Bid::STATUS_COMPLETE);
            $this->flashSuccess('Заявка исполнена');
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Response
     */
    public function actionWork($id): Response
    {
        try {
            $this->bidService->changeStatus($id, Bid::STATUS_IN_WORK);
            $this->flashSuccess('Заявка принята в работу');
        } catch (DomainException $ex) {
            $this->flashError($ex->getMessage());
        }

        return $this->redirect(['index']);
    }

    /**
     * @param $id
     *
     * @return Bid|null
     * @throws NotFoundHttpException
     */
    protected function findModel($id): ?Bid
    {
        if (($model = Bid::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

frontend/controllers/FrontendController.php
<?php

namespace frontend\controllers;

use frontend\helpers\CacheHelper;
use Yii;
use yii\web\Controller;
use yii\web\Response;

/**
 * Class FrontendController
 * @package frontend\controllers
 */
class FrontendController extends Controller
{
    protected $modelSearchClass = 'empty-search-class';

    /**
     * @param string $redirectTo
     *
     * @return Response
     */
    public function actionClearFilter(string $redirectTo = 'index'): Response
    {
        Yii::$app->cache->delete(CacheHelper::withUserPostfix($this->modelSearchClass));

        return $this->redirect([$redirectTo]);
    }
}

frontend/views/bid/_form.php
<?php

use frontend\forms\bid\BidForm;
use common\models\bid\Bid;
use common\models\department\Department;
use common\models\subdivision\Subdivision;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;
use yii\widgets\MaskedInput;

/**
 * @var $this View
 * @var $modelForm BidForm
 * @var $form ActiveForm
 * @var $lastAcceptedUser string
 */

$isAdmin = $this->params['global-is-admin'] ?? false;
?>

<div class="bid-form">
    <?php $form = ActiveForm::begin(); ?>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'number')->textInput([
                'disabled' => true,
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'accepted_user')->textInput([
                'class' => 'form-control js-input-content',
                'maxlength' => true,
            ])->label($modelForm->getAttributeLabel('accepted_user') . '&nbsp;' . '<span class="label-extend js-label-content">' . $lastAcceptedUser . '</span>') ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'applicant_user')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'department_id')->widget(Select2::class, [
                'data' => Department::getAllList([Department::ITC]),
                'pluginOptions' => [
                    'allowClear' => true,
                ],
                'options' => [
                    'placeholder' => '-----',
                    'multiple' => false
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <?= $form->field($modelForm, 'building')->input('number') ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($modelForm, 'floor')->dropDownList(Bid::getFloors(), ['prompt' => '---']) ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($modelForm, 'room')->textInput() ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($modelForm, 'phone')
                ->textInput(['placeholder' => '99-99'])
                ->widget(MaskedInput::class, [
                    'mask' => '99-99',
                ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <?= $form->field($modelForm, 'subdivision_id')->widget(Select2::class, [
                'data' => Subdivision::getListForSelect(),
                'pluginOptions' => [
                    'allowClear' => true,
                ],
                'options' => [
                    'placeholder' => '-----',
                    'multiple' => false
                ],
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'content')->textarea([
                'rows' => 3,
                'class' => 'form-control resize-both',
            ]) ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'note')->textarea([
                'rows' => 3,
                'class' => 'form-control resize-both',
            ]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-6">
            <?php if ($isAdmin) { ?>
                <?= $form->field($modelForm, 'status')->dropDownList(Bid::getRbacStatusLabelsForAdmin()) ?>
            <?php } else { ?>
                <?= $form->field($modelForm, 'status')->dropDownList(Bid::getRbacStatusLabels()) ?>
            <?php } ?>
        </div>
        <div class="col-sm-6">
            <?= $form->field($modelForm, 'date')
                ->textInput(['placeholder' => '9999-99-99 99:99'])
                ->widget(MaskedInput::class, [
                    'mask' => '9999-99-99 99:99',
                ]) ?>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>
    <?php $form::end(); ?>
</div>

frontend/views/bid/_search.php
<?php

use frontend\helpers\FilterHelper;
use common\models\bid\Bid;
use frontend\models\bid\BidSearch;
use common\models\department\Department;
use common\models\subdivision\Subdivision;
use kartik\date\DatePicker;
use kartik\select2\Select2;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\View;
use yii\widgets\MaskedInput;

/**
 * @var $this View
 * @var $model BidSearch
 * @var $form ActiveForm
 * @var $showFilter boolean
 */
?>

<div class="panel panel-default">
    <div class="panel-heading search-heading" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
        <h4 class="panel-title">
            <a class="accordion-toggle <?= $showFilter ? '' : 'collapsed' ?>" data-toggle="collapse"
               data-parent="#accordion" href="#collapseThree">Фильтр</a>
        </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse <?= $showFilter ? 'in' : '' ?>"
         data-filter-type="<?= FilterHelper::TYPE_BID_FILTER ?>">
        <div class="panel-body">
            <?php $form = ActiveForm::begin([
                'action' => ['index'],
                'method' => 'get',
            ]); ?>
            <div class="row">
                <div class="col-sm-3">
                    <?= $form->field($model, 'departmentId')->widget(Select2::class, [
                        'data' => Department::getAllList([Department::ITC]),
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => '-----',
                            'multiple' => false
                        ],
                    ]) ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'subdivisionId')->widget(Select2::class, [
                        'data' => Subdivision::getListForSelect(),
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => '-----',
                            'multiple' => false
                        ],
                    ]) ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'acceptedUser') ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'applicantUser') ?>
                </div>
                <div class="col-sm-2">
                    <?= $form->field($model, 'number') ?>
                </div>
                <div class="col-sm-2">
                    <?= $form->field($model, 'phone')
                        ->textInput(['placeholder' => '99-99'])
                        ->widget(MaskedInput::class, [
                            'mask' => '99-99',
                        ]) ?>
                </div>
                <div class="col-sm-2">
                    <?= $form->field($model, 'building')->textInput() ?>
                </div>
                <div class="col-sm-2">
                    <?= $form->field($model, 'floor')->widget(Select2::class, [
                        'data' => Bid::getFloors(),
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => '-----',
                            'multiple' => false
                        ],
                    ]) ?>
                </div>
                <div class="col-sm-2">
                    <?= $form->field($model, 'room') ?>
                </div>
                <div class="col-sm-2">
                    <?= $form->field($model, 'status')->widget(Select2::class, [
                        'data' => Bid::getFilterStatusLabels(),
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => '-----',
                            'multiple' => false
                        ],
                    ]) ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'dateFrom')->widget(DatePicker::class, [
                        'options' => [
                            'placeholder' => '',
                        ],
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd'
                        ]
                    ]); ?>
                </div>
                <div class="col-sm-3">
                    <?= $form->field($model, 'dateTo')->widget(DatePicker::class, [
                        'options' => [
                            'placeholder' => '',
                        ],
                        'pluginOptions' => [
                            'autoclose' => true,
                            'format' => 'yyyy-mm-dd'
                        ]
                    ]); ?>
                </div>
                <div class="col-sm-4">
                    <?= $form->field($model, 'isVisible')->widget(Select2::class, [
                        'data' => Bid::getVisibleLabels(),
                        'pluginOptions' => [
                            'allowClear' => true,
                        ],
                        'options' => [
                            'placeholder' => '-----',
                            'multiple' => false
                        ],
                    ]) ?>
                </div>
                <div class="col-sm-2">
                    <div class="form-group t-a-r m-t-25">
                        <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
                        <?= Html::a('Сбросить', ['/bid/clear-filter'], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/bid/create.php
<?php

use frontend\forms\bid\BidForm;
use yii\web\View;

/**
 * @var $this View
 * @var $modelForm BidForm
 * @var $lastAcceptedUser string
 */

$this->title = 'Создание заявки';
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="bid-create">
    <h1 class="t-a-c m-t-0">
        <?= h($this->title) ?>
    </h1>
    <?= $this->render('_form', compact('modelForm', 'lastAcceptedUser')) ?>
</div>

frontend/views/bid/index.php
<?php

use common\models\bid\Bid;
use frontend\models\bid\BidSearch;
use kartik\dynagrid\DynaGrid;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\View;
use yii\data\ActiveDataProvider;

/**
 * @var $this View
 * @var $searchModel BidSearch
 * @var $dataProvider ActiveDataProvider
 * @var $showFilter boolean
 */

$this->title = 'Заявки';
$this->params['breadcrumbs'][] = $this->title;

$user = Yii::$app->user->identity;
$isAdmin = $this->params['global-is-admin'] ?? false;

$columns = [
    [
        'class' => 'yii\grid\CheckboxColumn',
    ],
    [
        'attribute' => 'number',
        'label' => '№',
    ],
    [
        'attribute' => 'department_id',
        'value' => function (Bid $model) {
            return $model->department->name;
        }
    ],
    [
        'attribute' => 'accepted_user',
        'label' => 'Принял заявку',
    ],
    [
        'attribute' => 'applicant_user',
        'contentOptions' => ['style' => 'white-space: pre-wrap'],
    ],
    [
        'attribute' => 'date',
        'format' => 'raw',
        'value' => function (Bid $model) {
            return
                date('H:i', strtotime($model->date)) . '<br>' .
                date('d-m-Y', strtotime($model->date));
        }
    ],
    [
        'attribute' => 'content',
        'format' => 'raw',
        'contentOptions' => ['style' => 'white-space: pre-wrap'],
        'value' => function (Bid $model) {
            $content = h($model->content);
            if ($model->note) {
                $content .= '<div class="divider"></div>';
                $content .= h($model->note);
            }

            return $content;
        }
    ],
    [
        'attribute' => 'building',
        'label' => 'Место',
        'format' => 'raw',
        'contentOptions' => ['style' => 'white-space: pre-wrap'],
        'value' => function (Bid $model) {
            $marker = $model->subdivision
                ? Html::tag('i', null, [
                    'class' => 'fas fa-map-marker-alt text-color-light pointer',
                    'title' => h($model->subdivision->name),
                    'data' => [
                        'toggle' => 'tooltip',
                        'placement' => 'top',
                    ],
                ])
                : '';

            $view = '<a href="' . Url::to(['/bid/view', 'id' => $model->id]) . '">' . Html::tag('i', null, [
                    'class' => 'fas fa-eye',
                    'title' => 'Просмотр заявки',
                    'data' => [
                        'toggle' => 'tooltip',
                        'placement' => 'top',
                    ],
                ]) . '</a>';

            $phone = $model->phone
                ? '<i class="fa fa-phone"></i> <b>' . $model->phone
                : '';

            $building = 'Корпус:&nbsp;' . ($model->building ? $model->building : '---');
            $floor = 'Этаж:&nbsp;' . ($model->floor ? $model->floor : '---');
            $room = 'Помещение: ' . ($model->room ? $model->room : '---');

            return $phone . '&nbsp;' . $marker . '&nbsp;' . $view . '</b><br>' . $building . '. ' . $floor . '.' . '<br>' . $room;
        }
    ],
    [
        'attribute' => 'status',
        'label' => 'Статус',
        'format' => 'raw',
        'filter' => Bid::getStatusLabels(),
        'value' => function (Bid $model) {
            switch ($model->status) {
                case Bid::STATUS_ACTIVE:
                    return '<span class="label label-primary">' . $model->getStatusLabel() . '</span>';
                case Bid::STATUS_IN_WORK:
                    return '<span class="label label-warning">' . $model->getStatusLabel() . '</span>';
                case Bid::STATUS_COMPLETE:
                    return '<span class="label label-success">' . $model->getStatusLabel() . '</span>';
                case Bid::STATUS_NOT_COMPLETE:
                case Bid::STATUS_ARCHIVE:
                    return '<span class="label label-danger">' . $model->getStatusLabel() . '</span>';
                default:
                    return $model->getStatusLabel();
            }
        }
    ],
    [
        'class' => 'yii\grid\ActionColumn',
        'template' => '{work} {check} {update} {archive}',
        'buttons' => [
            'work' => function ($url, Bid $model) {
                if ($model->isActive()) {
                    return Html::a('<i class="fa fa-hammer"></i>', ['/bid/work', 'id' => $model['id']], [
                            'title' => 'Отметить как принятую в работу',
                            'class' => 'btn btn-xs btn-primary m-b-5',
                            'data-confirm' => 'Отметить заявку как принятую в работу?',
                        ]) . '<br>';
                }
                return '';
            },
            'check' => function ($url, Bid $model) {
                if ($model->isActive() || $model->isInWork()) {
                    return Html::a('<i class="fa fa-check"></i>', ['/bid/check', 'id' => $model['id']], [
                            'title' => 'Отметить как выполненное',
                            'class' => 'btn btn-xs btn-success m-b-5',
                            'data-confirm' => 'Отметить заявку как выполненную?',
                        ]) . '<br>';
                }
                return '';
            },
            'update' => function ($url, $model) {
                return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['/bid/update', 'id' => $model['id']], [
                    'title' => 'Обновить',
                    'class' => 'btn btn-xs btn-warning'
                ]);
            },
            'archive' => function ($url, Bid $model) use ($user) {
                if ($model->isArchive()) {
                    return '';
                }

                if ($user->isAdmin()) {
                    return Html::a('<i class="fa fa-archive"></i>', ['/bid/archive', 'id' => $model['id']], [
                        'title' => 'Архивировать',
                        'class' => 'btn btn-xs btn-danger',
                        'data-confirm' => 'Вы действительно хотите архивировать заявку?'
                    ]);
                }
                return '';
            },
        ],
    ],
];

$archivePackLink = $isAdmin
    ? Html::button('Скрыть', ['class' => 'btn btn-primary m-l-5 m-r-5 js-archive-bid'])
    : '';
?>

<h1 class="t-a-c m-t-0">
    <?= h($this->title) ?>
</h1>

<?= $this->render('_search', [
    'model' => $searchModel,
    'showFilter' => $showFilter,
]); ?>

<?= DynaGrid::widget([
    'columns' => $columns,
    'theme' => 'simple-default',
    'storage' => DynaGrid::TYPE_COOKIE,
    'gridOptions' => [
        'dataProvider' => $dataProvider,
        'panel' => [
            'heading' => '<h3 class="panel-title">' . $this->title . '</h3>',
            'before' => '<div class="dynagrid-buttons">' . '{dynagrid}' .
                Html::a('Добавить заявку', ['create'], ['class' => 'btn btn-success m-l-5 m-r-5']) .
                $archivePackLink . '</div>'
        ],
        'rowOptions' => function (Bid $model) {
            if ($model->isImportant()) {
                return [
                    'class' => 'color-light-red'
                ];
            }
        },
    ],
    'options' => [
        'id' => 'dynagrid-bid'
    ]
]); ?>

frontend/views/bid/update.php
<?php

use frontend\forms\bid\BidForm;
use common\models\bid\Bid;
use common\helpers\TextHelper;
use yii\web\View;

/**
 * @var $this View
 * @var $model Bid
 * @var $modelForm BidForm
 * @var $lastAcceptedUser string
 */

$this->title = 'Редактирование заявки: ' . TextHelper::getShortText($model->content, 75);
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => TextHelper::getShortText($model->content, 75), 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>

<div class="bid-update">
    <h1 class="m-t-0">
        <?= h($this->title) ?>
    </h1>

    <?= $this->render('_form', [
        'modelForm' => $modelForm,
        'lastAcceptedUser' => $lastAcceptedUser,
    ]) ?>
</div>

frontend/views/bid/view.php
<?php

use common\helpers\TextHelper;
use common\models\bid\Bid;
use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\web\View;

/**
 * @var $this View
 * @var $model Bid
 */

$this->title = TextHelper::getShortText($model->content, 75);
$this->params['breadcrumbs'][] = ['label' => 'Заявки', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
$user = Yii::$app->user->identity;
?>

<div class="bid-view">
    <h1 class="m-t-0">
        <?= h($this->title) ?>
    </h1>
    <p>
        <?php if ($model->isActive()) { ?>
            <?= Html::a('<i class="fa fa-check"></i> Отметить как выполненную', ['check', 'id' => $model->id], [
                'class' => 'btn btn-success',
                'data' => [
                    'confirm' => 'Отметить заявку как выполненную?',
                ],
            ]) ?>

            <?= Html::a('<i class="fa fa-hammer"></i> Взять в работу', ['work', 'id' => $model->id], [
                'class' => 'btn btn-success',
                'data' => [
                    'confirm' => 'Отметить заявку как принятую в работу?',
                ],
            ]) ?>
        <?php } ?>

        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['update', 'id' => $model->id], [
            'class' => 'btn btn-info',
            'title' => 'Редактировать',
        ]) ?>

        <?php if ($user->isAdmin() && !$model->isArchive()) { ?>
            <?= Html::a('<i class="fa fa-archive"></i>', ['archive', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'title' => 'Архивировать',
                'data' => [
                    'confirm' => 'Вы уверены что хотите архивировать данную заявку?',
                    'method' => 'post',
                ],
            ]) ?>
        <?php } ?>
    </p>

    <?php if ($model->statusHistory) { ?>
        <div class="panel panel-default">
            <div class="panel-heading search-heading" data-toggle="collapse" data-parent="#accordion"
                 href="#collapseThree">
                <h4 class="panel-title">
                    <a class="accordion-toggle"
                       data-toggle="collapse"
                       data-parent="#accordion"
                       href="#collapseThree">История статусов</a>
                </h4>
            </div>
            <div id="collapseThree" class="panel-collapse collapse">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th class="w25">Изменен пользователем</th>
                        <th class="w25">С</th>
                        <th class="w25">На</th>
                        <th class="w25">Дата</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($model->statusHistory as $statusHistory) { ?>
                        <tr>
                            <td><?= $statusHistory->user->username ?></td>
                            <td><?= $statusHistory->status_from ?></td>
                            <td><?= $statusHistory->status_to ?></td>
                            <td><?= date('d.m.Y H:i:s', strtotime($statusHistory->created_at)) ?></td>
                        </tr>
                    <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    <?php } ?>

    <?= DetailView::widget([
        'model' => $model,
        'options' => [
            'class' => 'table table-bordered detail-view col-width-50'
        ],
        'attributes' => [
            'number',
            'accepted_user',
            'applicant_user',
            [
                'attribute' => 'department_id',
                'value' => function (Bid $model) {
                    return $model->department ? $model->department->name : '---';
                }
            ],
            'content:ntext',
            'note:ntext',
            'building',
            'floor',
            'room:ntext',
            'phone',
            [
                'attribute' => 'subdivision_id',
                'value' => function (Bid $model) {
                    return $model->subdivision ? $model->subdivision->name : '---';
                }
            ],
            [
                'attribute' => 'status',
                'value' => function (Bid $model) {
                    return $model->getStatusLabel();
                }
            ],
            [
                'attribute' => 'date',
                'value' => function (Bid $model) {
                    return date('Y-m-d H:i', strtotime($model->date));
                }
            ],
            [
                'attribute' => 'updated_at',
                'value' => function (Bid $model) {
                    return date('Y-m-d H:i', strtotime($model->updated_at));
                }
            ],
        ],
    ]) ?>
</div>